### ISSUE TITLE
dojox chart themes

### ISSUE THREAD

**Issue by MichelleJean28** [Esri/calcite-maps-styler-template#6]
Hi,

Is it possible to simultaneously use 3 different custom dojox chart themes with the calcite-maps-styler-template? I need 3 pie charts, each with theme colors consistent with my tile layers.

I know I should use  `.setTheme` vor every `= new Chart` but I don't know where that could be integrated inside the calcite-maps-styler-template.

Just starting to learn to code, any help would be appreciated.

Michelle.

**Comment by alaframboise** [comment]
Where do you need them? In the default popup or in a panel? It should just work in popup and you could also customize the template to put them in a panel. It shouldn't be an issue.

**Comment by MichelleJean28** [comment]
Hi @alaframboise 

I need them in the default popup. I see that calcite-maps-styler-template uses Claro theme for dojox charting. I can't find any reference to Claro in the calcite-maps-styler-template files so I am not sure where to start from, where the code for new themes could be integrated.

Michelle.

**Comment by alaframboise** [comment]
@MichelleJean28 the template uses whatever theme the mapping API uses, this is not specific to Styler. If you are using ArcGIS JS 3.x, then the Calcite theme should be used, which has style overrides for Claro. If you are using ArcGIS JS 4.x, then the required styles for charting are loaded automatically with the API css.

**Comment by MichelleJean28** [comment]
Thank you @alaframboise. 
Styler looks great!
